# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Quickstart' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
  # Pods for Quickstart
	pod 'Alamofire', '~> 5.2'
	pod 'SnapKit', '~> 5.0.0'
	pod 'Bond'
	pod 'PromisedFuture'
	pod 'PKHUD', '~> 5.0'

  target 'QuickstartTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QuickstartUITests' do
    # Pods for testing
  end

end
