# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Quickstart' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Quickstart
  pod 'Alamofire', '~> 5.2'

  target 'QuickstartTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QuickstartUITests' do
    # Pods for testing
  end

end
